-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Lord Marrowgar", {
	[69057] = {"blue","yellow"},
	[69076] = "red",
	[69138] = "blue",
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Lord Marrowgar", {
	[69057] = "alert",
	[69076] = "long",
	[69138] = "underyou",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Lady Deathwhisper", {
	[70900] = "cyan",
	[70901] = "cyan",
	[71001] = "blue",
	[71204] = {"blue","orange"},
	[71237] = {"blue","red"},
	[71289] = {"blue","orange"},
	[71426] = "yellow",
	["adds"] = "cyan",
	["berserk"] = {"orange","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Lady Deathwhisper", {
	[70900] = "alert",
	[70901] = "alert",
	[71001] = "underyou",
	[71289] = "alarm",
	[71426] = "long",
	["adds"] = "info",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Icecrown Gunship Battle", {
	[69638] = {"blue","orange"},
	[69651] = {"blue","red"},
	["adds"] = "cyan",
	["mage"] = "yellow",
})

BigWigs:AddSounds("Icecrown Gunship Battle", {
	["adds"] = "info",
	["mage"] = "alarm",
})

BigWigs:AddColors("Deathbringer Saurfang", {
	[72293] = {"blue","yellow"},
	[72385] = {"blue","orange"},
	[72410] = {"blue","purple"},
	[72737] = "red",
	["adds"] = "cyan",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Deathbringer Saurfang", {
	[72293] = "alert",
	[72410] = "warning",
	[72737] = "long",
	["adds"] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Festergut", {
	[69165] = "yellow",
	[69195] = "yellow",
	[69240] = "red",
	[69279] = {"blue","orange"},
	[72219] = {"blue","green"},
	[72295] = "red",
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Festergut", {
	[69279] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Rotface", {
	[69508] = "red",
	[69674] = "blue",
	[69839] = "orange",
	["berserk"] = {"orange","red"},
	["ooze"] = "yellow",
})

BigWigs:AddSounds("Rotface", {
	[69508] = "alarm",
	[69839] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Professor Putricide", {
	[70351] = "yellow",
	[70447] = "blue",
	[70672] = "blue",
	[70911] = "blue",
	[71255] = "orange",
	[72295] = {"blue","yellow"},
	[72451] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
	["phase"] = {"green","red"},
})

BigWigs:AddSounds("Professor Putricide", {
	[70351] = "alert",
	[70911] = "alert",
	[72451] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Blood Prince Council", {
	[70981] = "green",
	[72037] = {"blue","orange"},
	[72039] = "red",
	[72040] = {"blue","orange"},
	[72052] = "yellow",
	[72999] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Blood Prince Council", {
	[70981] = "info",
	[72039] = "long",
	[72040] = "long",
	[72052] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Blood-Queen Lana'thel", {
	[70877] = "orange",
	[71265] = {"blue","yellow"},
	[71340] = {"blue","red"},
	[71623] = {"blue","yellow"},
	[71772] = "red",
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Blood-Queen Lana'thel", {
	[70877] = "alert",
	[71772] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Valithria Dreamwalker", {
	[69325] = "yellow",
	[71086] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["blazing"] = "green",
	["portal"] = "red",
})

BigWigs:AddSounds("Valithria Dreamwalker", {
	[71086] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Sindragosa", {
	[69762] = "blue",
	[69766] = "blue",
	[70106] = "blue",
	[70123] = "red",
	[70126] = {"blue","orange"},
	[70127] = "yellow",
	["airphase"] = "green",
	["berserk"] = {"orange","red","yellow"},
	["phase2"] = "green",
})

BigWigs:AddSounds("Sindragosa", {
	[69762] = "alert",
	[70123] = "alarm",
	[70127] = "info",
	["berserk"] = "alarm",
	["phase2"] = "long",
})

BigWigs:AddColors("The Lich King", {
	[68980] = {"blue","yellow"},
	[68981] = "orange",
	[69037] = {"blue","orange","yellow"},
	[69200] = "blue",
	[69409] = "blue",
	[70337] = "blue",
	[70372] = {"red","yellow"},
	[70498] = "orange",
	[70541] = "orange",
	[72143] = "yellow",
	[72262] = "orange",
	[72762] = {"blue","red"},
	[73529] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("The Lich King", {
	[68981] = "long",
	[69200] = "alert",
	[69409] = "alert",
	[70337] = "alert",
	[70372] = {"info","long"},
	[72143] = "alert",
	[72262] = "long",
	[72762] = {"alert","info"},
	["berserk"] = "alarm",
})

BigWigs:AddColors("Icecrown Citadel Trash", {
	[69483] = {"blue","red"},
	[71022] = "red",
	[71127] = {"blue","purple"},
})

BigWigs:AddSounds("Icecrown Citadel Trash", {
	[69483] = "warning",
	[71022] = "alarm",
	[71127] = "warning",
})

BigWigs:AddColors("The Beasts of Northrend", {
	[66317] = "blue",
	[66330] = "red",
	[66331] = {"blue","orange"},
	[66758] = "green",
	[66759] = "red",
	[66770] = {"blue","yellow"},
	[66823] = {"blue","orange"},
	[66869] = {"blue","orange"},
	[66883] = {"blue","yellow"},
	[68335] = "red",
	["berserk"] = {"orange","red","yellow"},
	["bosses"] = "green",
	["charge"] = "blue",
	["snobold"] = {"blue","yellow"},
	["spew"] = "yellow",
	["sprays"] = "red",
})

BigWigs:AddSounds("The Beasts of Northrend", {
	[66317] = "alarm",
	[66331] = "info",
	[66823] = "info",
	[66869] = "info",
	[66883] = "alarm",
	[68335] = "long",
	["berserk"] = "alarm",
	["charge"] = "alarm",
})

BigWigs:AddColors("Lord Jaraxxus", {
	[66197] = "blue",
	[66228] = "yellow",
	[66237] = {"blue","green","orange"},
	[66334] = "blue",
	["adds"] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Lord Jaraxxus", {
	[66197] = "alert",
	[66237] = "info",
	["adds"] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Faction Champions", {
	[65801] = {"blue","yellow"},
	[65816] = {"blue","orange"},
	[65877] = {"blue","yellow"},
	[65947] = "red",
	[65960] = {"blue","yellow"},
	[65980] = "red",
	[65983] = "red",
	[66010] = "orange",
	[67514] = "orange",
	[67777] = "orange",
})

BigWigs:AddSounds("Faction Champions", {
	[65816] = "alarm",
})

BigWigs:AddColors("The Twin Val'kyr", {
	["berserk"] = {"orange","red","yellow"},
	["shield"] = {"orange","red"},
	["touch"] = "blue",
	["vortex"] = {"blue","green"},
})

BigWigs:AddSounds("The Twin Val'kyr", {
	["berserk"] = "alarm",
	["shield"] = "alert",
	["touch"] = "info",
	["vortex"] = "alarm",
})

BigWigs:AddColors("Anub'arak", {
	[66013] = "blue",
	[66118] = "red",
	[66134] = "yellow",
	[67574] = "blue",
	["berserk"] = {"orange","red"},
	["burrow"] = {"orange","yellow"},
})

BigWigs:AddSounds("Anub'arak", {
	[66118] = "long",
	[67574] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Patchwerk", {
	[28131] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Patchwerk", {
	[28131] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Grobbulus", {
	[28169] = {"blue","red"},
	[28240] = "yellow",
	["adds"] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Grobbulus", {
	[28169] = "warning",
	[28240] = "info",
	["adds"] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Gluth", {
	[28371] = {"green","orange"},
	[28375] = "red",
	[29306] = "blue",
	[54378] = {"blue","purple"},
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Gluth", {
	[28371] = "alert",
	[28375] = "warning",
	[54378] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Thaddius", {
	[28059] = "blue",
	[28084] = "blue",
	[28089] = "orange",
	[28134] = "red",
	[28338] = "red",
	["berserk"] = {"orange","red"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Thaddius", {
	[28059] = "warning",
	[28084] = "warning",
	[28089] = "long",
	[28338] = "alert",
	["berserk"] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Noth the Plaguebringer", {
	[29208] = "yellow",
	[29212] = "blue",
	[29213] = {"green","red"},
	[29214] = "red",
	["adds"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Noth the Plaguebringer", {
	[29208] = "alert",
	[29213] = "warning",
	[29214] = "alarm",
	["adds"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Heigan the Unclean", {
	[29998] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Heigan the Unclean", {
	[29998] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Loatheb", {
	[29204] = {"orange","red","yellow"},
	[29234] = "green",
	[29865] = "yellow",
	[55593] = {"green","red"},
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Loatheb", {
	[29204] = {"alarm","long"},
	[29865] = "alert",
	[55593] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Anub'Rekhan", {
	[28783] = "orange",
	[28785] = {"green","red","yellow"},
	["add"] = "purple",
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Anub'Rekhan", {
	[28783] = "alert",
	[28785] = {"alarm","info","long"},
	["add"] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Grand Widow Faerlina", {
	[28732] = {"green","orange"},
	[28794] = "blue",
	[28798] = {"green","orange","red","yellow"},
})

BigWigs:AddSounds("Grand Widow Faerlina", {
	[28732] = "info",
	[28794] = "underyou",
	[28798] = "warning",
})

BigWigs:AddColors("Maexxna", {
	[28741] = "purple",
	[28747] = {"orange","red"},
	[28776] = {"blue","cyan"},
	[29484] = {"red","yellow"},
	["spiders"] = "yellow",
	["web_wrap"] = {"blue","orange","red","yellow"},
})

BigWigs:AddSounds("Maexxna", {
	[28747] = {"alarm","long"},
	[28776] = "info",
	[29484] = "info",
	["spiders"] = "alert",
	["web_wrap"] = {"alarm","warning"},
})

BigWigs:AddColors("Instructor Razuvious", {
	[29060] = {"green","yellow"},
	[29061] = {"green","yellow"},
	[55543] = {"orange","red"},
	[55550] = {"blue","cyan"},
})

BigWigs:AddSounds("Instructor Razuvious", {
	[29060] = "info",
	[55543] = {"alarm","alert"},
})

BigWigs:AddColors("Gothik the Harvester", {
	["add"] = {"orange","red","yellow"},
	["add_death"] = "red",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Gothik the Harvester", {
	["add_death"] = {"alert","info"},
	["stages"] = {"alarm","info","long"},
})

BigWigs:AddColors("The Four Horsemen", {
	[28863] = "orange",
	[28883] = "yellow",
	[28884] = "red",
	[57369] = {"blue","purple"},
	["berserk"] = {"orange","red","yellow"},
	["mark"] = "cyan",
	["stages"] = "green",
})

BigWigs:AddSounds("The Four Horsemen", {
	["berserk"] = "alarm",
})

BigWigs:AddColors("Sapphiron", {
	[28522] = {"blue","yellow"},
	[28524] = "red",
	[28542] = "yellow",
	[55699] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Sapphiron", {
	[28524] = "alarm",
	[28542] = "alert",
	[55699] = "underyou",
	["berserk"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Kel'Thuzad Naxxramas", {
	[27808] = {"blue","red","yellow"},
	[27810] = "red",
	[27819] = {"blue","yellow"},
	[28410] = {"blue","orange","red"},
	["guardians"] = "red",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Kel'Thuzad Naxxramas", {
	[27808] = "alert",
	[27819] = "alert",
	[28410] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Flame Leviathan", {
	[62374] = "blue",
	[62396] = "orange",
	[62475] = "green",
})

BigWigs:AddSounds("Flame Leviathan", {
	[62374] = "alarm",
	[62475] = "long",
})

BigWigs:AddColors("Ignis the Furnace Master", {
	[62382] = "green",
	[62488] = "red",
	[62717] = {"blue","red"},
	[63472] = "yellow",
	[63474] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Ignis the Furnace Master", {
	[62382] = "info",
	[62488] = "warning",
	[62717] = "alert",
	[63472] = "long",
	[63474] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Razorscale", {
	[64021] = "yellow",
	[64733] = "blue",
	[64771] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
	["harpoon"] = "yellow",
	["stages"] = {"cyan","green","yellow"},
})

BigWigs:AddSounds("Razorscale", {
	[64021] = "warning",
	[64733] = "alarm",
	[64771] = "info",
	["berserk"] = "alarm",
	["harpoon"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("XT-002 Deconstructor", {
	[62776] = "yellow",
	[63849] = "yellow",
	[64193] = "orange",
	[64234] = {"blue","red"},
	[65121] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("XT-002 Deconstructor", {
	[62776] = "warning",
	[63849] = "long",
	[64193] = "info",
	[64234] = "alert",
	[65121] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("The Iron Council", {
	[61869] = "yellow",
	[61887] = {"blue","yellow"},
	[61903] = "orange",
	[61974] = "green",
	[62269] = "blue",
	[62273] = "yellow",
	[62274] = "yellow",
	[63483] = "yellow",
	[64637] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("The Iron Council", {
	[61869] = "long",
	[61887] = "alarm",
	[62269] = "alarm",
	[64637] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Kologarn", {
	[63355] = {"blue","purple"},
	[63983] = "orange",
	[64290] = {"blue","yellow"},
	["arm"] = "yellow",
	["eyebeam"] = {"blue","red"},
})

BigWigs:AddSounds("Kologarn", {
	[63355] = "info",
	[64290] = "alert",
	["eyebeam"] = "info",
})

BigWigs:AddColors("Algalon the Observer", {
	[64122] = "green",
	[64412] = {"blue","orange"},
	[64443] = {"red","yellow"},
	[64597] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Algalon the Observer", {
	[64412] = "alert",
	[64443] = "alarm",
	[64597] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Auriaya", {
	[64386] = {"orange","yellow"},
	[64396] = {"blue","yellow"},
	[64678] = "red",
	[64688] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["defender"] = "yellow",
})

BigWigs:AddSounds("Auriaya", {
	[64386] = "info",
	[64396] = "alert",
	[64678] = "long",
	[64688] = "warning",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Hodir", {
	[61968] = {"blue","orange","yellow"},
	[62039] = "blue",
	[63512] = "red",
	[65133] = {"blue","green"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Hodir", {
	[61968] = {"alert","long"},
	[62039] = "alert",
	[65133] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Thorim", {
	[62016] = "orange",
	[62017] = "blue",
	[62042] = {"blue","orange"},
	[62130] = {"blue","yellow"},
	[62279] = "yellow",
	[62331] = {"blue","red"},
	[62338] = "orange",
	[62526] = {"blue","red"},
	[62942] = "yellow",
	["berserk"] = {"orange","red","yellow"},
	["hardmode"] = "cyan",
	["stages"] = "yellow",
})

BigWigs:AddSounds("Thorim", {
	[62017] = "info",
	[62338] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Freya", {
	[62437] = {"blue","yellow"},
	[62589] = "blue",
	[62623] = {"blue","yellow"},
	[62861] = {"blue","yellow"},
	[62865] = {"blue","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "red",
	["tree"] = "orange",
	["wave"] = "green",
})

BigWigs:AddSounds("Freya", {
	[62437] = "long",
	[62589] = "alert",
	[62861] = "info",
	[62865] = "alarm",
	["berserk"] = "alarm",
	["tree"] = "alarm",
})

BigWigs:AddColors("Mimiron", {
	[63274] = {"blue","red"},
	[63631] = "red",
	[63811] = "red",
	[64444] = {"blue","green","red"},
	[64529] = {"red","yellow"},
	[64570] = "red",
	[64623] = "red",
	["berserk"] = {"orange","red"},
	["phase"] = "yellow",
})

BigWigs:AddSounds("Mimiron", {
	[63274] = "long",
	[63811] = "alert",
	[64444] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("General Vezax", {
	[62660] = {"blue","orange"},
	[62661] = "yellow",
	[62662] = "red",
	[63276] = {"blue","orange"},
	["animus"] = "red",
	["berserk"] = {"orange","red","yellow"},
	["vapor"] = "green",
	["vaporstack"] = "blue",
})

BigWigs:AddSounds("General Vezax", {
	[62660] = "alert",
	[62661] = "warning",
	[62662] = "long",
	[63276] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Yogg-Saron", {
	[62979] = "green",
	[63050] = "blue",
	[63120] = {"blue","yellow"},
	[63138] = {"blue","orange"},
	[63802] = "blue",
	[63830] = {"blue","yellow"},
	[64059] = "orange",
	[64126] = {"blue","green"},
	[64163] = "red",
	[64189] = "yellow",
	[64465] = {"green","red"},
	["berserk"] = {"orange","red","yellow"},
	["portal"] = "green",
	["small_tentacles"] = "red",
	["stages"] = {"red","yellow"},
	["tentacle"] = "red",
	["weakened"] = "green",
})

BigWigs:AddSounds("Yogg-Saron", {
	[63138] = "alert",
	[63802] = "warning",
	[63830] = "alert",
	[64059] = "warning",
	[64163] = "warning",
	["berserk"] = "alarm",
	["stages"] = "alarm",
	["weakened"] = "long",
})

BigWigs:AddColors("Archavon the Stone Watcher", {
	[58663] = {"green","yellow"},
	[58678] = {"blue","red"},
	[58965] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["charge"] = {"blue","yellow"},
})

BigWigs:AddSounds("Archavon the Stone Watcher", {
	[58965] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Malygos", {
	[57429] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["breath"] = {"red","yellow"},
	["phase"] = "yellow",
	["sparkbuff"] = "red",
	["sparks"] = {"red","yellow"},
	["surge"] = "blue",
	["vortex"] = "yellow",
})

BigWigs:AddSounds("Malygos", {
	["berserk"] = "alarm",
	["breath"] = "alert",
	["sparks"] = "alert",
	["surge"] = "alarm",
})

BigWigs:AddColors("Sartharion", {
	[57491] = "red",
	[58793] = "yellow",
	[58835] = {"blue","green"},
	[59127] = "yellow",
	[60430] = {"blue","purple"},
	["acolyte_shadron"] = "orange",
	["acolyte_vesperon"] = "orange",
	["berserk"] = {"orange","red","yellow"},
	["drakes"] = "yellow",
})

BigWigs:AddSounds("Sartharion", {
	[57491] = "warning",
	[58793] = "info",
	[58835] = "long",
	[59127] = "alert",
	["acolyte_shadron"] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Emalon the Storm Watcher", {
	[64216] = "yellow",
	[64218] = "green",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Emalon the Storm Watcher", {
	["berserk"] = "alarm",
})

BigWigs:AddColors("Koralon the Flame Watcher", {
	[66665] = {"green","yellow"},
	[66684] = "blue",
	[66725] = "yellow",
})

BigWigs:AddSounds("Koralon the Flame Watcher", {
	[66684] = "alarm",
})

BigWigs:AddColors("Toravon the Ice Watcher", {
	[72004] = {"blue","orange"},
	[72034] = {"green","yellow"},
	[72090] = "blue",
	[72091] = "red",
})

BigWigs:AddSounds("Toravon the Ice Watcher", {
})

BigWigs:AddColors("Onyxia", {
	[17086] = "red",
	[18392] = "blue",
	[18431] = "yellow",
	[18435] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Onyxia", {
	[17086] = "warning",
	[18392] = "alarm",
	[18431] = "info",
	[18435] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Halion", {
	[74525] = "orange",
	[74562] = {"blue","yellow"},
	[74630] = "blue",
	[74648] = {"blue","red"},
	[74769] = "red",
	[74792] = {"blue","yellow"},
	[74802] = "blue",
	[74806] = "orange",
	[74826] = "cyan",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Halion", {
	[74562] = "warning",
	[74630] = "underyou",
	[74648] = {"long","underyou"},
	[74769] = "alert",
	[74792] = "warning",
	[74802] = "underyou",
	[74826] = "warning",
	["berserk"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("The Ruby Sanctum Trash", {
	[40504] = "yellow",
	[74367] = {"blue","purple"},
	[74384] = "yellow",
	[74403] = "red",
	[74453] = {"blue","yellow"},
	[74502] = {"blue","orange"},
	[74509] = "orange",
	[75125] = "red",
	[78722] = {"green","orange"},
	["adds"] = "cyan",
})

BigWigs:AddSounds("The Ruby Sanctum Trash", {
	[40504] = "alert",
	[74367] = "alarm",
	[74384] = "alert",
	[74403] = "info",
	[74453] = "warning",
	[74502] = "warning",
	[74509] = "long",
	[75125] = "info",
	[78722] = "alarm",
	["adds"] = "long",
})
