sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "YM1TLOJP1IBOy76eDStblNleP4NtmNW5kPxUB6ZQKyLcJYbOfUVn2FJx5h097nFo/1TP4JbkYs+Rixi1BgJZrS29rQfO2XUlJoLqi7JwyV+Pw4FG00p5X2XMM2MCXETdggOE2kSQW6/RxF31lGmmeQm0da8cbaexK2GiC9pjgyz/pb5FnO7e0CQLnQikilOEq3UeOeApzw3GW+DyHWWT3wFBaKx1WTVIIahmm7MppsKdOT+RG8NFiYJAs876LxQqPYQT8XX8ADy5AqgdorCeqRI/kFx5juta+X/+FibdYgB3MMNqFMbuSe+UgbH4azkKekkuwYqNUgndCxDezv0EEtYP0olnBYGGK+lhdRv3JRkWw7RQCTyl62EUaO+C7f7mcv0j0Il6g0WJ/UhhbwPQ+HjASGWsEAIzip+v1ayOQiB102bR9/saRlO/bUypjpPeqL0qRJYulEWEaDv0A+ZPUKXX/fd/R6DkWeBpgN0lACTr9fyoHdJ1t2OsZjKFgQmZZLLG2RL/RI8t3rzUq9DkKCJrIA8nR9g7Rj/tMT7+M+rFXnPlli8SSu5I3X1UZq39E3DcO4pPRIi9bUItLLH/ySmjV8LuySzPyRRAi9mG3zF5brcAv1ejv+XpdMLAuHFNl4v6BTZ5ajtL+PHCi2RKC6JNzSVgKDbeaExdMKLxGtI="
  - secure: "c6mIYEBMo3YYTeMm9xqynJmwJX0TAMBMLymZDKA9xe35XeIzIrqEBNMd2OPxS3lftscHLFGgVUocvnwDKa8cUxLf0ECuBAvoqO3tJ8nxheG68IUt7Lbu0o4sbxiXReD+xR6KeHEPW6ucGH69cgG0ExIVHbH2ny7I6mVkARsyyErbOO7+N3jN5lnxdNfIYPR8qraMecw2Z91izSuoyu0eZbMYS4gCXPGv+Yrs/QZSvkXL7XDJ47ECZSfpD4n/ISljYFkbKmwJGVZuMujZUWlW/2wOFQrmt4vmEnB0XEeZNilxGAXhtY29FGePwJwf20gbMlx7RT3bAq7PGe5snh+SsvGl0/CeeVv+syUeO8n04ATVX8DSduHueGou44ECrM4syuFaqqXABD8/RN/aEPpVDxmz1nfqxi5I/gOn3Ut4RO0ry5sGrkAAKRb/mfKDYMoBYhfHyk5IlEAr96EWtRMZmtXFl/iWcoLxgXKRRVUsGB9nEIGqqkzWBFPTMuIG0pD0YbtRDSYvhGV4jILyG1U2LziZ7jdZk8lmtqtejI2ShILWrGj2+RfSN8WMZaBUcMEuQcUutggdrSbxo7xZQZMLMbZk5OSzh6NSsYSQaQDpUceFLxwlJm9TZHWBQQR+7w4LcSJavGcjFmie+IoW9gXneUkSC4jC3R6VScxoc3iA0Es="
  - secure: "VLr9dtPXikYrHUZlEabSOO4J5lkRgvi9sxrwEeAv5A0Tdl5CQRPD7ENWFbuw4I3IrJ5q+51GT7boLP81HWkELrqPz7KHneTkxlG8z/28GIiXq1hZMmVJ/7sa8enAUDXFXtwywpCXeDbWZCkrgZjoEeNio6OpdO6yX6uF7RflMqjbJefcN5AUBc7gXZ5KRNZRTf8zMiR4ID9a2zXTJ5EQtZY5SofhdrCnFanlNkhrNn4xAXC+Q+esYOoP4o3wWfHkpzJYz3YpaW5vPzgMV+UfkLlGkSFTnaiiODPUhoyGEB2dNQhLuq4Tcyyo5sA4P9g3lNVmdOxCWcB0JSchIU/hHrf0FA13KMxt30ROCm+AbJ3duK6css7c2sy4zXYWVmTAVnmioNcu76Alw9GrTawKXVdyYnNkI0NxISh/BK4HasQo0XrNkBY6VNhbN5P4PkaapKklSqtlCdy8BLIDHRlN1zx40cL2gVLTpfcLCfiua+pbUaWMwqPmCjWTimxkM4/irFAFugpOJM5IqqT3BROa/wO6amUmn6L2KFYG3gfrNv3EkbhANePd8W4pEHLzWy+mmSkpMPly7IGTBkvqVZjm8adpDko0ykF7HuHqoH83il1FkBITVKvoj504OP1M908cCd/tM6jwNtPczHRdFtLNw0w2xKBlNkJD47Bo5kjCWxE="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
