sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "DJv9SdEcrSYsv5rZDNDUIezI11QyFjcfnmkJI5YZ75BkoKRMOYsPgggQKPgtlJd3LuohAUPBOIksjD+p16TSP9/5ndWOKcrVQOLBlkwT55UtrV46p2B6PWrJZUGsgsDon3b2YtIOf3xMsKQyfTe2C2V8m83Ij/bG/s+zhNBlZ2RUnr+uDX1f9a+91M3QvU3is7M58iwxr4rpWBrihvZig5j/ig+Xctdi6Ow+MyQMp3kpmSbfEfQC1dPDvjwslHElTYAMVuiU7cgOh41AW+Lv8RpaNGaTm26miFS8rZHHAd8xYM8bb+UTbzqUL1tntmF5qM3izB3tCnSlu0BTj+tzOSWCartF4KMed/2cWTDrP2O0metFI9vKqpAWTWI4kqLl34CkALc0Ufe9RlOJrLOjs73RRApeDX+NANTJqE+WH1NqOzBRNTb7KPJL82FoU03baTAjfLRJbzx6rRKAqoqWf7njG2Wypxd6zCJfHYdaayKE5tMlteoyN5mu67H66wHhJPejhgD1B77Ldg2Uc+K0uq9+Hsy+F4o5AQ2QMevytMfB4RrA6+9qrXnnbW7Tth01DVj/qFNtuW2GGDTgbfCc1uwkL/Qm8IlbbJFSKCfC07CXZLw+OIcIPddqqq8QClyK9gz5JPLhbwraDOlc0l5qWiNAZMy+ai8e69nZLirjbT0="
  - secure: "c6mIYEBMo3YYTeMm9xqynJmwJX0TAMBMLymZDKA9xe35XeIzIrqEBNMd2OPxS3lftscHLFGgVUocvnwDKa8cUxLf0ECuBAvoqO3tJ8nxheG68IUt7Lbu0o4sbxiXReD+xR6KeHEPW6ucGH69cgG0ExIVHbH2ny7I6mVkARsyyErbOO7+N3jN5lnxdNfIYPR8qraMecw2Z91izSuoyu0eZbMYS4gCXPGv+Yrs/QZSvkXL7XDJ47ECZSfpD4n/ISljYFkbKmwJGVZuMujZUWlW/2wOFQrmt4vmEnB0XEeZNilxGAXhtY29FGePwJwf20gbMlx7RT3bAq7PGe5snh+SsvGl0/CeeVv+syUeO8n04ATVX8DSduHueGou44ECrM4syuFaqqXABD8/RN/aEPpVDxmz1nfqxi5I/gOn3Ut4RO0ry5sGrkAAKRb/mfKDYMoBYhfHyk5IlEAr96EWtRMZmtXFl/iWcoLxgXKRRVUsGB9nEIGqqkzWBFPTMuIG0pD0YbtRDSYvhGV4jILyG1U2LziZ7jdZk8lmtqtejI2ShILWrGj2+RfSN8WMZaBUcMEuQcUutggdrSbxo7xZQZMLMbZk5OSzh6NSsYSQaQDpUceFLxwlJm9TZHWBQQR+7w4LcSJavGcjFmie+IoW9gXneUkSC4jC3R6VScxoc3iA0Es="
  - secure: "VLr9dtPXikYrHUZlEabSOO4J5lkRgvi9sxrwEeAv5A0Tdl5CQRPD7ENWFbuw4I3IrJ5q+51GT7boLP81HWkELrqPz7KHneTkxlG8z/28GIiXq1hZMmVJ/7sa8enAUDXFXtwywpCXeDbWZCkrgZjoEeNio6OpdO6yX6uF7RflMqjbJefcN5AUBc7gXZ5KRNZRTf8zMiR4ID9a2zXTJ5EQtZY5SofhdrCnFanlNkhrNn4xAXC+Q+esYOoP4o3wWfHkpzJYz3YpaW5vPzgMV+UfkLlGkSFTnaiiODPUhoyGEB2dNQhLuq4Tcyyo5sA4P9g3lNVmdOxCWcB0JSchIU/hHrf0FA13KMxt30ROCm+AbJ3duK6css7c2sy4zXYWVmTAVnmioNcu76Alw9GrTawKXVdyYnNkI0NxISh/BK4HasQo0XrNkBY6VNhbN5P4PkaapKklSqtlCdy8BLIDHRlN1zx40cL2gVLTpfcLCfiua+pbUaWMwqPmCjWTimxkM4/irFAFugpOJM5IqqT3BROa/wO6amUmn6L2KFYG3gfrNv3EkbhANePd8W4pEHLzWy+mmSkpMPly7IGTBkvqVZjm8adpDko0ykF7HuHqoH83il1FkBITVKvoj504OP1M908cCd/tM6jwNtPczHRdFtLNw0w2xKBlNkJD47Bo5kjCWxE="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
